framework:
  github: vlang/v
  version: weekly.2024.06

  build_deps:
    - libatomic1

  bootstrap:
    - cd /opt/vlang && git fetch --all --tags && git checkout tags/weekly.2024.06 && make && v -version && cd /app

  build_flags:
    - -prod -cc gcc
